version: '2'

volumes:
  nextcloud:

services:
   app:
    image: nextcloud
    ports:
      - 8080:80
    environment:
      - SQLITE_DATABASE=NextCloudSQLiteDb
    volumes:
      - nextcloud:/var/www/html
    restart: always